### ISSUE TITLE
"Nexus stream error"

### ISSUE THREAD

**Issue by susilehtola** [felipec/msn-pecan#1]
Hi,

I've been receiving a lot of "Unable to authenticate: nexus stream error" messages lately. Have you seen this, yet..?

**Comment by dneto** [comment]
Yes, I've been receiving this message too, it's looks like the server isn't supporting MSNP12 anymore, so msn-pecan will need several updates. For more information you can see [issue 299](http://code.google.com/p/msn-pecan/issues/detail?id=299&colspec=ID%20Type%20Status%20Priority%20Stars%20Milestone%20Owner%20Summary) on [project page](http://code.google.com/p/msn-pecan/).

**Comment by felipec** [comment]
Yeah, hopefully it's a server glitch, but I'll try to upgrade to new versions of the protocol to see how much is needed to upgrade.

**Comment by felipec** [comment]
It's fixed now on 0.1.2.
